name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  bw_clientid:
    description: 'Bitwarden Client Id'
    required: true
  bw_clientsecret:
    description: 'Bitwarden Client Secret'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -e BW_CLIENTID=${{ inputs.bw_clientid }}
    - -e BW_CLIENTSECRET=${{ inputs.bw_clientsecret }}